name: asset_yug_debugging
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.7
  image: ^4.2.0
  path_provider: ^2.1.3
  mongo_dart: ^0.10.0
  # open_file: ^3.3.2
  open_file_plus: ^3.4.1+1
  intl: ^0.19.0
  table_calendar: ^3.1.0
  fixnum: ^1.1.0
  riverpod: ^2.5.0
  badges: ^3.1.2
  firebase_core: ^3.5.0
  # firebase_auth: ^5.3.0
  firebase_auth: ^5.3.0
  mobile_scanner: ^5.1.1
  rename: ^3.0.2
  http: ^1.2.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.0
  hive:
  hive_flutter:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  rxdart: ^0.28.0
  file_picker: ^8.0.7
  device_info_plus: ^11.2.0
  universal_io: ^2.2.2



flutter_native_splash:
  color: "#42a5f5"  # Background color of the splash screen
  image: assets/images/asset_yug_logo.png  # Path to your splash screen image
  android: true  # Include Android platform
  ios: true  # Include iOS platform
  web: true
  android_gravity: center  # Gravity for Android splash screen image
  ios_content_mode: scaleAspectFill  # Content mode for iOS splash screen image
  # android_fullscreen: true  # Enable full screen mode for Android
  # ios_fullscreen: true  # Enable full screen mode for iOS


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/

