// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Sc2phplqNbTyjVWJ6rziTfwMEF2xpU8',
    appId: '1:526139496135:web:1d91fe51cbb1b22a2c10e2',
    messagingSenderId: '526139496135',
    projectId: 'assetyug-da946',
    authDomain: 'assetyug-da946.firebaseapp.com',
    storageBucket: 'assetyug-da946.appspot.com',
    measurementId: 'G-BMRT81DWJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoo5452ayxMjyJi3SVsvx8GBqwMkiG5ew',
    appId: '1:526139496135:android:a9d9f9120cb47d942c10e2',
    messagingSenderId: '526139496135',
    projectId: 'assetyug-da946',
    storageBucket: 'assetyug-da946.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDAfbqSwXVwgJOPVIvhqapgcJOwQQm_pY',
    appId: '1:526139496135:ios:23ef187380decd992c10e2',
    messagingSenderId: '526139496135',
    projectId: 'assetyug-da946',
    storageBucket: 'assetyug-da946.appspot.com',
    iosBundleId: 'com.example.assetYugDebugging',
  );

}